apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: remove-dangling-cron-job
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: remove-dangling
            image: uzyexe/curl
            command:
            - sh
            - "-c"
            - curl -X DELETE ${KUBERNETES_RO_SERVICE_HOST}:${KUBERNETES_RO_SERVICE_PORT}/api/v1/namespaces/default/pods?labelSelector=state%3Ddangling;
            env:
            - name: KUBERNETES_RO_SERVICE_HOST
              value: 127.0.0.1
            - name: KUBERNETES_RO_SERVICE_PORT
              value: '8001'
            volumeMounts:
            - name: test-volume
              mountPath: "/mount/test-volume"
          - name: kubectl
            image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
            imagePullPolicy: Always
            args:
            - proxy
            - "-p"
            - '8001'
          volumes:
          - name: test-volume
            emptyDir: {}