apiVersion: v1
kind: Service
metadata:
  name: app-engine-service
  labels:
    run: app-engine
spec:
  ports:
  - name: app-engine-port
    port: 3000
    protocol: TCP
  - name: app-engine-controller-port
    port: 2626
    protocol: TCP    
  selector:
    app: app-engine
    state: inactive
  type: LoadBalancer